export const authTypes = {
    SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USER_SIGNUP_REQUEST',
    SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
    ACTIVATION_REQUEST: 'USER_ACTIVATION_REQUEST',
    ACTIVATION_SUCCESS:'USER_ACTIVATION_SUCCESS',
    ACTIVATION_FAIL:'USER_ACTIVATION_FAIL',
    LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE : 'USER_LOGIN_FAILURE',
    PASSWORRESET_REQUEST:'USER_PASSWORD_RESET_REQUEST',
    PASSWORRESET_SUCCESS:'USER_PASSWORD_RESET_SUCCESS',
    PASSWORRESET_FAIL:'USER_PASSWORD_RESET_FAIL',
}