export const passwordResetConfirmTypes = {
    PASSWORRESETCONFIRM_REQUEST:'USER_PASSWORD_RESET_CONFIRM_REQUEST',
    PASSWORRESETCONFIRM_SUCCESS:'USER_PASSWORD_RESET_CONFIRM_SUCCESS',
    PASSWORRESETCONFIRM_FAIL:'USER_PASSWORD_RESET_CONFIRM_FAIL',
}